import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Image from 'next/image';
import Link from 'next/link';
import FileUpload from './components/FileUpload';
import './globals.css';
import SearchInput from './components/SearchInput';
const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <div className="min-h-screen flex flex-col">
                    {/* Header with logo */}
                    <header className="border-b">
                        <div className="container mx-auto p-4 flex justify-between items-center">
                            <Link href="/">
                                <img
                                    src="https://chunkify.s3.us-east-1.amazonaws.com/logos/chunkify.png"
                                    alt="Chunkify Logo"
                                    width={180}
                                    height={70}
                                />
                            </Link>
                            <SearchInput />
                            <FileUpload />
                        </div>
                    </header>

                    {/* Main content */}
                    <main className="flex-1">{children}</main>
                </div>
            </body>
        </html>
    );
}
